In [116]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/nlp-getting-started/sample_submission.csv
/kaggle/input/nlp-getting-started/train.csv
/kaggle/input/nlp-getting-started/test.csv


In [117]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings("ignore")

In [118]:
train=pd.read_csv("/kaggle/input/nlp-getting-started/train.csv")
test=pd.read_csv("/kaggle/input/nlp-getting-started/test.csv")
submission=pd.read_csv("/kaggle/input/nlp-getting-started/sample_submission.csv")

In [119]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   id        7613 non-null   int64 
 1   keyword   7552 non-null   object
 2   location  5080 non-null   object
 3   text      7613 non-null   object
 4   target    7613 non-null   int64 
dtypes: int64(2), object(3)
memory usage: 297.5+ KB


In [120]:
train.duplicated().sum()

0

In [121]:
train.isna().sum()

id             0
keyword       61
location    2533
text           0
target         0
dtype: int64

In [122]:
train

id keyword location  \
0         1     NaN      NaN   
1         4     NaN      NaN   
2         5     NaN      NaN   
3         6     NaN      NaN   
4         7     NaN      NaN   
...     ...     ...      ...   
7608  10869     NaN      NaN   
7609  10870     NaN      NaN   
7610  10871     NaN      NaN   
7611  10872     NaN      NaN   
7612  10873     NaN      NaN   

                                                   text  target  
0     Our Deeds are the Reason of this #earthquake M...       1  
1                Forest fire near La Ronge Sask. Canada       1  
2     All residents asked to 'shelter in place' are ...       1  
3     13,000 people receive #wildfires evacuation or...       1  
4     Just got sent this photo from Ruby #Alaska as ...       1  
...                                                 ...     ...  
7608  Two giant cranes holding a bridge collapse int...       1  
7609  @aria_ahrary @TheTawniest The out of control w...       1  
7610  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...       1  
7611  Police investigating after an e-bike collided ...       1  
7612  The Latest: More Homes Razed by Northern Calif...       1  

[7613 rows x 5 columns]

In [123]:
train['keyword'].unique()

array([nan, 'ablaze', 'accident', 'aftershock', 'airplane%20accident',
       'ambulance', 'annihilated', 'annihilation', 'apocalypse',
       'armageddon', 'army', 'arson', 'arsonist', 'attack', 'attacked',
       'avalanche', 'battle', 'bioterror', 'bioterrorism', 'blaze',
       'blazing', 'bleeding', 'blew%20up', 'blight', 'blizzard', 'blood',
       'bloody', 'blown%20up', 'body%20bag', 'body%20bagging',
       'body%20bags', 'bomb', 'bombed', 'bombing', 'bridge%20collapse',
       'buildings%20burning', 'buildings%20on%20fire', 'burned',
       'burning', 'burning%20buildings', 'bush%20fires', 'casualties',
       'casualty', 'catastrophe', 'catastrophic', 'chemical%20emergency',
       'cliff%20fall', 'collapse', 'collapsed', 'collide', 'collided',
       'collision', 'crash', 'crashed', 'crush', 'crushed', 'curfew',
       'cyclone', 'damage', 'danger', 'dead', 'death', 'deaths', 'debris',
       'deluge', 'deluged', 'demolish', 'demolished', 'demolition',
       'derail', 'der

In [124]:
train['location'].unique()

array([nan, 'Birmingham', 'Est. September 2012 - Bristol', ...,
       'Vancouver, Canada', 'London ', 'Lincoln'], dtype=object)

In [125]:
train.drop(columns=['id','keyword','location'],axis=1,inplace=True)

In [126]:
train

text  target
0     Our Deeds are the Reason of this #earthquake M...       1
1                Forest fire near La Ronge Sask. Canada       1
2     All residents asked to 'shelter in place' are ...       1
3     13,000 people receive #wildfires evacuation or...       1
4     Just got sent this photo from Ruby #Alaska as ...       1
...                                                 ...     ...
7608  Two giant cranes holding a bridge collapse int...       1
7609  @aria_ahrary @TheTawniest The out of control w...       1
7610  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...       1
7611  Police investigating after an e-bike collided ...       1
7612  The Latest: More Homes Razed by Northern Calif...       1

[7613 rows x 2 columns]

In [127]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

In [128]:
train

text  target
0     Our Deeds are the Reason of this #earthquake M...       1
1                Forest fire near La Ronge Sask. Canada       1
2     All residents asked to 'shelter in place' are ...       1
3     13,000 people receive #wildfires evacuation or...       1
4     Just got sent this photo from Ruby #Alaska as ...       1
...                                                 ...     ...
7608  Two giant cranes holding a bridge collapse int...       1
7609  @aria_ahrary @TheTawniest The out of control w...       1
7610  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...       1
7611  Police investigating after an e-bike collided ...       1
7612  The Latest: More Homes Razed by Northern Calif...       1

[7613 rows x 2 columns]

In [129]:
train['text']=train['text'].apply(lambda x:word_tokenize(x))

In [130]:
train['text']=train['text'].apply(lambda x:[a.lower().strip() for a in x])

In [131]:
import string
train['text']=train['text'].apply(lambda x:[a for a in x if a not in string.punctuation])

In [132]:
stopwords=stopwords.words("english")
stopwords.remove("no")

In [133]:
train['text']=train['text'].apply(lambda x:[a for a in x if a not in stopwords ])

In [134]:
train

text  target
0     [deeds, reason, earthquake, may, allah, forgiv...       1
1         [forest, fire, near, la, ronge, sask, canada]       1
2     [residents, asked, 'shelter, place, notified, ...       1
3     [13,000, people, receive, wildfires, evacuatio...       1
4     [got, sent, photo, ruby, alaska, smoke, wildfi...       1
...                                                 ...     ...
7608  [two, giant, cranes, holding, bridge, collapse...       1
7609  [aria_ahrary, thetawniest, control, wild, fire...       1
7610  [m1.94, 01:04, utc, 5km, volcano, hawaii, http...       1
7611  [police, investigating, e-bike, collided, car,...       1
7612  [latest, homes, razed, northern, california, w...       1

[7613 rows x 2 columns]

In [135]:
from nltk.stem import PorterStemmer
stem=PorterStemmer()
train['text']=train['text'].apply(lambda x:[stem.stem(a) for a in x])

In [136]:
train['target'].value_counts()

target
0    4342
1    3271
Name: count, dtype: int64

In [137]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer()

In [138]:
train

text  target
0     [deed, reason, earthquak, may, allah, forgiv, us]       1
1          [forest, fire, near, la, rong, sask, canada]       1
2     [resid, ask, 'shelter, place, notifi, offic, n...       1
3     [13,000, peopl, receiv, wildfir, evacu, order,...       1
4     [got, sent, photo, rubi, alaska, smoke, wildfi...       1
...                                                 ...     ...
7608  [two, giant, crane, hold, bridg, collaps, near...       1
7609  [aria_ahrari, thetawniest, control, wild, fire...       1
7610  [m1.94, 01:04, utc, 5km, volcano, hawaii, http...       1
7611  [polic, investig, e-bik, collid, car, littl, p...       1
7612  [latest, home, raze, northern, california, wil...       1

[7613 rows x 2 columns]

In [139]:
train['text']=train['text'].apply(lambda x:' '.join(x))

In [147]:
tfidf_matrix = vectorizer.fit_transform(train['text'])

# Convert TF-IDF matrix to DataFrame
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer.get_feature_names_out())

# Concatenate TF-IDF DataFrame with target column
#tfidf_df['target'] = train['target']

In [148]:
tfidf_df

00       000  0000  007npen6lg  00cy9vxeff  00end  00pm        01   02  \
0     0.0  0.000000   0.0         0.0         0.0    0.0   0.0  0.000000  0.0   
1     0.0  0.000000   0.0         0.0         0.0    0.0   0.0  0.000000  0.0   
2     0.0  0.000000   0.0         0.0         0.0    0.0   0.0  0.000000  0.0   
3     0.0  0.458131   0.0         0.0         0.0    0.0   0.0  0.000000  0.0   
4     0.0  0.000000   0.0         0.0         0.0    0.0   0.0  0.000000  0.0   
...   ...       ...   ...         ...         ...    ...   ...       ...  ...   
7608  0.0  0.000000   0.0         0.0         0.0    0.0   0.0  0.000000  0.0   
7609  0.0  0.000000   0.0         0.0         0.0    0.0   0.0  0.000000  0.0   
7610  0.0  0.000000   0.0         0.0         0.0    0.0   0.0  0.307329  0.0   
7611  0.0  0.000000   0.0         0.0         0.0    0.0   0.0  0.000000  0.0   
7612  0.0  0.000000   0.0         0.0         0.0    0.0   0.0  0.000000  0.0   

      0215  ...   ûò  ûò800000  ûòthe  ûòåêcnbc   ûó  ûóher  ûókodi  ûóneglig  \
0      0.0  ...  0.0       0.0    0.0       0.0  0.0    0.0     0.0       0.0   
1      0.0  ...  0.0       0.0    0.0       0.0  0.0    0.0     0.0       0.0   
2      0.0  ...  0.0       0.0    0.0       0.0  0.0    0.0     0.0       0.0   
3      0.0  ...  0.0       0.0    0.0       0.0  0.0    0.0     0.0       0.0   
4      0.0  ...  0.0       0.0    0.0       0.0  0.0    0.0     0.0       0.0   
...    ...  ...  ...       ...    ...       ...  ...    ...     ...       ...   
7608   0.0  ...  0.0       0.0    0.0       0.0  0.0    0.0     0.0       0.0   
7609   0.0  ...  0.0       0.0    0.0       0.0  0.0    0.0     0.0       0.0   
7610   0.0  ...  0.0       0.0    0.0       0.0  0.0    0.0     0.0       0.0   
7611   0.0  ...  0.0       0.0    0.0       0.0  0.0    0.0     0.0       0.0   
7612   0.0  ...  0.0       0.0    0.0       0.0  0.0    0.0     0.0       0.0   

      ûótech  ûów  
0        0.0  0.0  
1        0.0  0.0  
2        0.0  0.0  
3        0.0  0.0  
4        0.0  0.0  
...      ...  ...  
7608     0.0  0.0  
7609     0.0  0.0  
7610     0.0  0.0  
7611     0.0  0.0  
7612     0.0  0.0  

[7613 rows x 18853 columns]

In [149]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [150]:
X_train,X_test,y_train,y_test=train_test_split(tfidf_df,train['target'],test_size=0.3)

In [151]:
model=GaussianNB()

In [152]:
model.fit(X_test,y_test)

GaussianNB()

In [153]:
y_pred=model.predict(X_test)

In [154]:
from sklearn.metrics import accuracy_score,confusion_matrix,recall_score,precision_score

In [155]:
accuracy_score(y_test,y_pred)

0.9640980735551664

In [156]:
precision_score(y_test,y_pred)

0.9224952741020794

In [157]:
confusion_matrix(y_test,y_pred)

array([[1226,   82],
       [   0,  976]])